updating regex

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -19,13 +19,13 @@ jobs:
             COMMIT_SHA=$(echo $commit | jq '.sha')
             COMMIT_MESSAGE=$(echo $commit | jq '.commit.message')
             echo "Validating new commit: ${COMMIT_SHA} - ${COMMIT_MESSAGE}"
-            if [[ "$COMMIT_MESSAGE" != *"AB#*"* ]]; then
-              echo ""
-              echo ""
-              echo "Pull request contains invalid commit: ${COMMIT_SHA}. This commit lacks an AB#xxx in the message, in the expected format: AB#xxx -- failing operation."
-              exit 1
+            if [[ "$COMMIT_MESSAGE" != *"AB"#""[0-9]""* ]]; then
+                echo ""
+                echo ""
+                echo "Pull request contains invalid commit: ${COMMIT_SHA}. This commit lacks an AB#xxx in the message, in the expected format: AB#xxx -- failing operation."
+                exit 1
+            else echo "valid commit"
             fi
-            echo "valid commit"
             COMMIT_MESSAGE=${COMMIT_MESSAGE#*\[}
             ISSUE=${COMMIT_MESSAGE%\]*}
             if [ $ISSUE == "" ]
